INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice replied.', 'http://lorempixel.com/200/200/food/', 'This was not a moment like a mouse, That he met in the same size for going through the door, and tried to open them.', 1, 1486, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice began a.', 'http://lorempixel.com/200/200/food/', 'And so she tried hard to whistle to it; but she stopped hastily, for the fan and gloves, and, as there was enough of.', 5, 2023, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice said.', 'http://lorempixel.com/200/200/food/', 'Alice for protection. You shant be able! I shall only look up in great fear lest she should chance to be sure; but I.', 1, 973, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice.', 'http://lorempixel.com/200/200/food/', 'Duchess; and the moral of that dark hall, and wander about among those beds of bright flowers and those cool.', 5, 1020, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice to.', 'http://lorempixel.com/200/200/food/', 'VERY turn-up nose, much more like a frog; and both the hedgehogs were out of it, and burning with curiosity, she ran.', 9, 2485, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'I didnt!.', 'http://lorempixel.com/200/200/food/', 'If I or she should meet the real Mary Ann, what ARE you doing out here? Run home this moment, I tell you, you coward!.', 5, 1671, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'King. Nearly.', 'http://lorempixel.com/200/200/food/', 'Hatter. He wont stand beating. Now, if you drink much from a bottle marked poison, so Alice went on in a VERY.', 4, 1485, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'There was an.', 'http://lorempixel.com/200/200/food/', 'Dodo solemnly, rising to its feet, ran round the neck of the Lobster Quadrille, that she began thinking over all the.', 7, 2537, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'The further.', 'http://lorempixel.com/200/200/food/', 'Hatter went on again: Twenty-four hours, I THINK; or is it twelve? I-- Oh, dont talk about cats or dogs either, if.', 6, 854, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'And how to.', 'http://lorempixel.com/200/200/food/', 'For instance, suppose it were white, but there was no one listening, this time, as it turned round and get ready to.', 5, 2837, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice by the.', 'http://lorempixel.com/200/200/food/', 'English! said the sage, as he spoke, and added with a great hurry to get rather sleepy, and went on to her ear..', 4, 735, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Shell get.', 'http://lorempixel.com/200/200/food/', 'King put on his flappers, --Mystery, ancient and modern, with Seaography: then Drawling--the Drawling-master was an.', 7, 320, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'And Alice.', 'http://lorempixel.com/200/200/food/', 'Caterpillar took the hookah into its eyes were nearly out of the Lobster; I heard him declare, \"You have baked me too.', 1, 904, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'And she found.', 'http://lorempixel.com/200/200/food/', 'Alice said very humbly; I wont indeed! said the Rabbits voice; and Alice could think of nothing better to say than.', 1, 2210, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'So Alice was.', 'http://lorempixel.com/200/200/food/', 'Five, in a few minutes it puffed away without being invited, said the King, and dont be nervous, or Ill have you.', 7, 973, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Dormouse, who.', 'http://lorempixel.com/200/200/food/', 'Pigeon in a sulky tone, as it is. Then you may SIT down, the King said, for about the right thing to get to, said.', 9, 1529, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'But the month.', 'http://lorempixel.com/200/200/food/', 'Alice thought the poor animals feelings. I quite agree with you, said the last word with such sudden violence that.', 3, 1945, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Mock Turtle.', 'http://lorempixel.com/200/200/food/', 'OURS they had been jumping about like mad things all this grand procession, came THE KING AND QUEEN OF HEARTS. Alice.', 1, 274, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Alice, as a.', 'http://lorempixel.com/200/200/food/', 'Twinkle, twinkle--\" Here the Queen added to one of them bowed low. Would you tell me, said Alice, surprised at.', 7, 2619, 9);
INSERT INTO Products (CompanyId, ProductName, ImageURL, ProductDescription, CostPrice, SalePrice, Inventory) VALUES (1, 'Dodo said,.', 'http://lorempixel.com/200/200/food/', 'Alice felt that it might end, you know, the Mock Turtle, they--youve seen them, of course? Yes, said Alice, very.', 7, 706, 9);


